# Image source
FROM node:lts

# Docker working directory
WORKDIR /app

# Copying file into APP directory of docker
COPY ./package.json ./package-lock.json /app/

# Then install the NPM module
RUN npm install

# Copy current directory to APP folder
COPY . /app/

# env declaration
ENV NODE_ENV=development

EXPOSE 3000
CMD ["npm", "run", "start:dev"]